// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wcs.Infrastructure.Persistence;

#nullable disable

namespace Wcs.Infrastructure.Migrations
{
    [DbContext(typeof(WcsDbContext))]
    partial class WcsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Wcs.Domain.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Args")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Wcs.Domain.Equipment.EquipmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastStatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeedRpm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperatureRaw")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Wcs.Domain.Field.FieldTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("BitIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldTags");

                    b.HasData(
                        new
                        {
                            Id = "CV01_RUN_FB",
                            Address = (ushort)0,
                            DataType = 0,
                            Description = "컨베이어1 구동 피드백",
                            DeviceId = "PLC01",
                            Direction = 0,
                            EquipmentId = "CV01",
                            PropertyName = "IsRunning"
                        },
                        new
                        {
                            Id = "CV01_FAULT",
                            Address = (ushort)0,
                            DataType = 1,
                            Description = "컨베이어1 Fault 상태",
                            DeviceId = "PLC01",
                            Direction = 0,
                            EquipmentId = "CV01",
                            PropertyName = "HasFault"
                        },
                        new
                        {
                            Id = "CV01_PE_IN",
                            Address = (ushort)1,
                            DataType = 1,
                            Description = "컨베이어1 입구 포토센서",
                            DeviceId = "PLC01",
                            Direction = 0,
                            EquipmentId = "CV01",
                            PropertyName = "IsBlocked"
                        },
                        new
                        {
                            Id = "CV02_SPEED",
                            Address = (ushort)0,
                            DataType = 2,
                            Description = "CV02 속도 (rpm)",
                            DeviceId = "PLC02",
                            Direction = 0,
                            EquipmentId = "CV02",
                            PropertyName = "SpeedRpm"
                        },
                        new
                        {
                            Id = "CV02_TEMP",
                            Address = (ushort)0,
                            DataType = 3,
                            Description = "CV02 온도 (Raw 값)",
                            DeviceId = "PLC02",
                            Direction = 0,
                            EquipmentId = "CV02",
                            PropertyName = "TemperatureRaw"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
